### ISSUE TITLE
More user-friendly custom registry API 

### ISSUE THREAD

**Issue by christopher-dG** [bcbi/CompatHelper.jl#123]
Currently you have to write some slightly obscure Julia code to add custom registries before the bot does its main thing. Maybe registry cloning could be done less directly via configuration? For example:
```yml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CUSTOM_REGISTRIES: https://github.com/A/B,https://github.com/C/D
```

It looks like we don't actually need the UUID and name of the registry, only the URL.
