### ISSUE TITLE
CompatHelper PRs don't trigger Github CI action

### ISSUE THREAD

**Issue by dkarrasch** [bcbi/CompatHelper.jl#190]
This is a fantastic tool, thank you for creating and maintaining it. Recently, I switched to CI via Github actions, and, unfortunately, CompatHelper's PRs don't trigger the CI action. This is the code in the `ci.yml`
```yml
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
```
that I found somewhere in the ecosystem and simply copied it. Do I need to add anything? Is it related to the fact that CompatHelper is not a "collaborator" of the package, and the same problem is likely to occur with any "external PR"? Any guidance would be much appreciated.
