### ISSUE TITLE
Wrap the package in the action template?

### ISSUE THREAD

**Issue by SaschaMann** [bcbi/CompatHelper.jl#32]
It might be useful to turn this into a "proper" action in addition to the Julia package/script that's run in the workflow. See [julia-buildpkg](https://github.com/julia-actions/julia-buildpkg/blob/master/src/main.ts) for an example. Once set up, the action repo would not change if it just executes the commands that are currently called manually in the workflow, so while there's some initial overhead, it wouldn't require ongoing maintenance.

This could simplify the workflow to

```yaml
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: bcbi/compat-helper-action@latest
        with:
          # config
```

and would allow you to publish it on the marketplace which could improve discoverability for people who don't follow the Julia community forums that closely. It may also be easier to set it up using the interactive workflow builder, but I haven't tried the new one out yet. People who prefer the current way would still be able to use it since the action would be a separate repo.

I'm not sure what UX people prefer in their workflows, just throwing it out there as a suggestion.
